const bookieUrls = {
    "888Aviator Zm": "",
    "1xbet Ng": "https://1xbet.ng/en",
    "1xbet Cm": "https://1xbet.cm/en",
    "BetPawa Cm": "https://betpawa.cm",
    "BetPawa Gh": "https://www.betpawa.gh",
    "BetPawa Ke": "",
    "BetPawa Mw": "",
    "BetPawa Ng": "https://www.betpawa.gh",
    "BetPawa Tg": "",
    "BetPawa Ug": "",
    "BetPawa Za": "",
    "BetPawa Zm": "",
    "BetWay Gh": "",
    "BetWay Ke": "",
    "BetWay Mw": "",
    "BetWay Ng": "",
    "BetWay Tg": "",
    "BetWay Ug": "",
    "Betika Mw": "",
    "Betlion Zm": "",
    "BolaBet Zm": "",
    "BongoBongo Zm": "",
    "GSB Zm": "",
    "MWOS Zm": "",
    "PariPesa Ng": "",
    "PariPesa Zm": "",
    "PariPesa Cm": "",
    "SportyBet Gh": "",
    "SportyBet Ng": "https://www.sportybet.com/ng/",
    "SportyBet Tg": ""
  };
  
  export default bookieUrls;